version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.internal.dilon.me'
    environment:
      GITLAB_OMNIBUS_CONFIG:
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.internal.dilon.me'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'

